"""adicionando nova tabela e coluna

Revision ID: d090c2fe54da
Revises: eb381ddca48e
Create Date: 2026-01-17 00:36:25.762323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd090c2fe54da'
down_revision: Union[str, Sequence[str], None] = 'eb381ddca48e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_codes', sa.Column('code', sa.String(), nullable=True))
    op.drop_column('email_codes', 'code_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_codes', sa.Column('code_hash', sa.VARCHAR(), nullable=True))
    op.drop_column('email_codes', 'code')
    # ### end Alembic commands ###
