"""adicionando nova tabela e coluna

Revision ID: eb381ddca48e
Revises: f50878e69d52
Create Date: 2026-01-17 00:29:43.795833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb381ddca48e'
down_revision: Union[str, Sequence[str], None] = 'f50878e69d52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_codes',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('code_hash', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_codes')
    # ### end Alembic commands ###
